use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

struct FontCandidate {
    path: PathBuf,
    family: String,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let token_dir = Path::new("resources/var");
    for file in [
        "Light.tokens.json",
        "Dark.tokens.json",
        "Spacing.tokens.json",
        "Shape.tokens.json",
        "Typography.tokens.json",
        "Layout.tokens.json",
    ] {
        println!("cargo:rerun-if-changed={}", token_dir.join(file).display());
    }

    let Some(out_dir) = env::var_os("OUT_DIR") else {
        panic!("OUT_DIR is not set");
    };
    let out_dir = PathBuf::from(out_dir);
    generate_figma_tokens(token_dir, &out_dir);

    println!("cargo:rerun-if-env-changed=VIEWKIT_UI_FONT_PATH");
    println!("cargo:rerun-if-env-changed=VIEWKIT_MONOSPACE_FONT_PATH");
    println!("cargo:rerun-if-env-changed=VIEWKIT_UI_FONT_FAMILY");
    println!("cargo:rerun-if-env-changed=VIEWKIT_MONOSPACE_FONT_FAMILY");

    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("mochios") {
        return;
    }

    let candidate = required_font("VIEWKIT_UI_FONT_PATH", "Inter Variable");
    let monospace = required_font("VIEWKIT_MONOSPACE_FONT_PATH", "UDEV Gothic");

    let target_path = out_dir.join("default_ui_font.ttf");
    fs::copy(&candidate.path, &target_path)
        .unwrap_or_else(|err| panic!("failed to copy default font: {err}"));
    let monospace_target_path = out_dir.join("default_monospace_font.ttf");
    fs::copy(&monospace.path, &monospace_target_path)
        .unwrap_or_else(|err| panic!("failed to copy default monospace font: {err}"));

    println!(
        "cargo:rustc-env=VIEWKIT_DEFAULT_UI_FONT_FAMILY={}",
        candidate.family
    );
    println!(
        "cargo:rustc-env=VIEWKIT_DEFAULT_MONOSPACE_FONT_FAMILY={}",
        monospace.family
    );
}

fn generate_figma_tokens(token_dir: &Path, out_dir: &Path) {
    let light = read_json(&token_dir.join("Light.tokens.json"));
    let dark = read_json(&token_dir.join("Dark.tokens.json"));
    let spacing = read_json(&token_dir.join("Spacing.tokens.json"));
    let shape = read_json(&token_dir.join("Shape.tokens.json"));
    let typography = read_json(&token_dir.join("Typography.tokens.json"));
    let layout = read_json(&token_dir.join("Layout.tokens.json"));

    let mut generated = String::from(
        "// @generated by build.rs from resources/var/*.tokens.json.\n\
         // Do not edit this file directly.\n\n",
    );
    emit_color_theme(&mut generated, "FIGMA_LIGHT_COLORS", &light);
    emit_color_theme(&mut generated, "FIGMA_DARK_COLORS", &dark);

    writeln!(
        generated,
        "pub const FIGMA_SPACING: FigmaSpacingTokens = FigmaSpacingTokens {{\n\
         space_2: {}, space_4: {}, space_8: {}, space_12: {}, space_16: {},\n\
         space_24: {}, space_32: {}, space_40: {}, space_48: {}, space_64: {},\n\
         }};",
        number(&spacing, &["Spacing", "2"]),
        number(&spacing, &["Spacing", "4"]),
        number(&spacing, &["Spacing", "8"]),
        number(&spacing, &["Spacing", "12"]),
        number(&spacing, &["Spacing", "16"]),
        number(&spacing, &["Spacing", "24"]),
        number(&spacing, &["Spacing", "32"]),
        number(&spacing, &["Spacing", "40"]),
        number(&spacing, &["Spacing", "48"]),
        number(&spacing, &["Spacing", "64"]),
    )
    .expect("write generated spacing tokens");

    writeln!(
        generated,
        "pub const FIGMA_SHAPE: FigmaShapeTokens = FigmaShapeTokens {{\n\
         radius_small: {}, radius_medium: {}, radius_large: {}, radius_xlarge: {},\n\
         stroke_default: {},\n\
         }};",
        number(&shape, &["Radius", "Small"]),
        number(&shape, &["Radius", "Medium"]),
        number(&shape, &["Radius", "Large"]),
        number(&shape, &["Radius", "XLarge"]),
        number(&shape, &["Stroke", "Default"]),
    )
    .expect("write generated shape tokens");

    writeln!(
        generated,
        "pub const FIGMA_TYPOGRAPHY: FigmaTypographyTokens = FigmaTypographyTokens {{\n\
         display_large: {}, display_medium: {}, title_large: {}, title_medium: {},\n\
         title_small: {}, body: {}, label: {}, caption: {},\n\
         }};",
        typography_expr(&typography, &["Typography", "Display", "Large"]),
        typography_expr(&typography, &["Typography", "Display", "Medium"]),
        typography_expr(&typography, &["Typography", "Title", "Large"]),
        typography_expr(&typography, &["Typography", "Title", "Medium"]),
        typography_expr(&typography, &["Typography", "Title", "Small"]),
        typography_expr(&typography, &["Typography", "Body"]),
        typography_expr(&typography, &["Typography", "Label"]),
        typography_expr(&typography, &["Typography", "Caption"]),
    )
    .expect("write generated typography tokens");

    writeln!(
        generated,
        "pub const FIGMA_LAYOUT: FigmaLayoutTokens = FigmaLayoutTokens {{\n\
         toolbar_height: {}, sidebar_width: {}, page_margin: {}, content_max_width: {},\n\
         form_width: {}, section_gap: {},\n\
         }};",
        number(&layout, &["Layout", "Toolbar", "Height"]),
        number(&layout, &["Layout", "Sidebar", "Width"]),
        number(&layout, &["Layout", "Page", "Margin"]),
        number(&layout, &["Layout", "Content", "MaxWidth"]),
        number(&layout, &["Layout", "Form", "Width"]),
        number(&layout, &["Layout", "Section", "Gap"]),
    )
    .expect("write generated layout tokens");

    fs::write(out_dir.join("figma_tokens.rs"), generated)
        .unwrap_or_else(|error| panic!("failed to write generated Figma tokens: {error}"));
}

fn emit_color_theme(output: &mut String, name: &str, root: &Value) {
    writeln!(
        output,
        "pub const {name}: FigmaColorTokens = FigmaColorTokens {{\n\
         accent: AccentColorTokens {{ primary: {}, hover: {}, pressed: {}, subtle: {}, on_accent: {} }},\n\
         background: BackgroundColorTokens {{ primary: {}, secondary: {}, elevated: {} }},\n\
         text: TextColorTokens {{ primary: {}, secondary: {}, tertiary: {}, disabled: {} }},\n\
         border: BorderColorTokens {{ default: {}, subtle: {}, strong: {} }},\n\
         semantic: SemanticColorTokens {{ warning: {}, success: {}, information: {}, error: ErrorColorTokens {{ base: {}, hover: {}, pressed: {}, disabled: {} }} }},\n\
         }};",
        color(root, &["Accent", "Primary"]),
        color(root, &["Accent", "Hover"]),
        color(root, &["Accent", "Pressed"]),
        color(root, &["Accent", "Subtle"]),
        color(root, &["Accent", "OnAccent"]),
        color(root, &["Background", "Primary"]),
        color(root, &["Background", "Secondary"]),
        color(root, &["Background", "Elevated"]),
        color(root, &["Text", "Primary"]),
        color(root, &["Text", "Secondary"]),
        color(root, &["Text", "Tertiary"]),
        color(root, &["Text", "Disabled"]),
        color(root, &["Border", "Default"]),
        color(root, &["Border", "Subtle"]),
        color(root, &["Border", "Strong"]),
        color(root, &["Semantic", "Warning"]),
        color(root, &["Semantic", "Success"]),
        color(root, &["Semantic", "Information"]),
        color(root, &["Semantic", "Error", "$root"]),
        color(root, &["Semantic", "Error", "Hover"]),
        color(root, &["Semantic", "Error", "Pressed"]),
        color(root, &["Semantic", "Error", "Disabled"]),
    )
    .expect("write generated color tokens");
}

fn read_json(path: &Path) -> Value {
    let source = fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    serde_json::from_str(&source)
        .unwrap_or_else(|error| panic!("invalid token JSON in {}: {error}", path.display()))
}

fn value_at<'a>(root: &'a Value, path: &[&str]) -> &'a Value {
    let mut value = root;
    for segment in path {
        value = value.get(*segment).unwrap_or_else(|| {
            panic!("missing Figma token path {}", path.join("/"));
        });
    }
    value
}

fn number(root: &Value, path: &[&str]) -> String {
    let value = value_at(root, path)
        .get("$value")
        .and_then(Value::as_f64)
        .unwrap_or_else(|| panic!("Figma token {} must be a number", path.join("/")));
    format!("{:?}_f32", value as f32)
}

fn integer(root: &Value, path: &[&str]) -> u16 {
    let value = value_at(root, path)
        .get("$value")
        .and_then(Value::as_u64)
        .unwrap_or_else(|| panic!("Figma token {} must be an integer", path.join("/")));
    u16::try_from(value)
        .unwrap_or_else(|_| panic!("Figma token {} does not fit in u16", path.join("/")))
}

fn color(root: &Value, path: &[&str]) -> String {
    let token = value_at(root, path);
    let value = token
        .get("$value")
        .unwrap_or_else(|| panic!("Figma token {} has no $value", path.join("/")));
    let hex = value
        .get("hex")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("Figma token {} must contain a hex color", path.join("/")));
    let rgb = u32::from_str_radix(hex.trim_start_matches('#'), 16)
        .unwrap_or_else(|_| panic!("Figma token {} has an invalid hex color", path.join("/")));
    let alpha = value.get("alpha").and_then(Value::as_f64).unwrap_or(1.0);
    if !(0.0..=1.0).contains(&alpha) {
        panic!("Figma token {} has an invalid alpha", path.join("/"));
    }
    let alpha = (alpha * 255.0).round() as u32;
    format!("Color::from_rgba_hex(0x{:08X})", (rgb << 8) | alpha)
}

fn typography_expr(root: &Value, path: &[&str]) -> String {
    let mut font_size = path.to_vec();
    font_size.push("FontSize");
    let mut font_weight = path.to_vec();
    font_weight.push("FontWeight");
    let mut line_height = path.to_vec();
    line_height.push("LineHeight");
    format!(
        "TypographyToken {{ font_size: {}, font_weight: {}, line_height: {} }}",
        number(root, &font_size),
        integer(root, &font_weight),
        number(root, &line_height),
    )
}

fn required_font(path_variable: &str, default_family: &'static str) -> FontCandidate {
    let Some(path) = env::var_os(path_variable) else {
        panic!("{path_variable} must point to a font file when building ViewKit for mochiOS");
    };
    let candidate = FontCandidate {
        path: PathBuf::from(path),
        family: (match path_variable {
            "VIEWKIT_UI_FONT_PATH" => env::var("VIEWKIT_UI_FONT_FAMILY"),
            _ => env::var("VIEWKIT_MONOSPACE_FONT_FAMILY"),
        })
        .unwrap_or_else(|_| default_family.to_owned()),
    };
    println!("cargo:rerun-if-changed={}", candidate.path.display());
    if !candidate.path.is_file() {
        panic!("{path_variable} does not point to a readable font file");
    }
    candidate
}
