[package]
name = "viewkit"
description = "A UI kit for mochiOS"
repository = "https://github.com/mochiOS/ViewKit"
homepage = "https://github.com/mochiOS/ViewKit"
keywords = ["uikit", "mochios", "viewkit", "ui", "kagami"]
categories = ["gui"]
license = "Apache-2.0"
version = "1.0.1"
edition = "2024"
autoexamples = false
build = "build.rs"

[dependencies]
cosmic-text = { version = "0.19.0", default-features = false, features = ["std", "swash"] }
thiserror = "2.0.18"
ui_layout = "0.9.8"
image = {
    version = "0.25.10",
    default-features = false,
    features = ["png", "jpeg", "webp"]
}
resvg = {
    version = "0.47.0",
    default-features = false,
}
tiny-skia = "0.12.0"

[target.'cfg(target_os = "linux")'.dependencies]
winit = {
    version = "0.30.13",
    default-features = false,
    features = [
        "wayland",
        "wayland-dlopen",
        "x11",
        "x11-dl",
        "rwh_06",
    ],
}
softbuffer = {
    version = "0.4.8",
    default-features = false,
    features = ["wayland", "wayland-dlopen", "x11", "x11-dlopen"],
}

[target.'cfg(target_os = "windows")'.dependencies]
winit = {
    version = "0.30.13",
    default-features = false,
    features = ["rwh_06"],
}
softbuffer = { version = "0.4.8", default-features = false }

[target.'cfg(target_os = "mochios")'.dependencies]
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
mochios-viewkit-gpu-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-viewkit-gpu-protocol" }

[lib]
name = "viewkit"
crate-type = ["cdylib", "rlib"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("mochios"))'] }

[[example]]
name = "button"
path = "examples/button.rs"

[[example]]
name = "text"
path = "examples/text.rs"

[[example]]
name = "scroll"
path = "examples/scroll.rs"

[[example]]
name = "border"
path = "examples/border.rs"

[[example]]
name = "text_field"
path = "examples/text_field.rs"

[[example]]
name = "all"
path = "examples/all.rs"

[[example]]
name = "image"
path = "examples/image.rs"

[[example]]
name = "svg"
path = "examples/svg.rs"
