#ifndef VIEWKIT_ABI_H
#define VIEWKIT_ABI_H

/* This file is automatically generated. Do not edit directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define VK_Z_ALIGNMENT_TOP_LEADING 0

#define VK_Z_ALIGNMENT_TOP 1

#define VK_Z_ALIGNMENT_TOP_TRAILING 2

#define VK_Z_ALIGNMENT_LEADING 3

#define VK_Z_ALIGNMENT_CENTER 4

#define VK_Z_ALIGNMENT_TRAILING 5

#define VK_Z_ALIGNMENT_BOTTOM_LEADING 6

#define VK_Z_ALIGNMENT_BOTTOM 7

#define VK_Z_ALIGNMENT_BOTTOM_TRAILING 8

#define VK_ABI_VERSION_MAJOR 1

#define VK_ABI_VERSION_MINOR 0

#define VK_ABI_VERSION_PATCH 0

#define VK_ABI_VERSION (((VK_ABI_VERSION_MAJOR << 16) | (VK_ABI_VERSION_MINOR << 8)) | VK_ABI_VERSION_PATCH)

#define VK_LENGTH_AUTO 0

#define VK_LENGTH_FIXED 1

#define VK_RECTANGLE_COLOR_BACKGROUND 0

#define VK_RECTANGLE_COLOR_SURFACE 1

#define VK_RECTANGLE_COLOR_ELEVATED_SURFACE 2

#define VK_RECTANGLE_COLOR_ACCENT 3

#define VK_RECTANGLE_COLOR_DESTRUCTIVE 4

#define VK_RECTANGLE_COLOR_CUSTOM 5

#define VK_CORNER_RADIUS_NONE 0

#define VK_CORNER_RADIUS_SMALL 1

#define VK_CORNER_RADIUS_MEDIUM 2

#define VK_CORNER_RADIUS_LARGE 3

#define VK_CORNER_RADIUS_EXTRA_LARGE 4

#define VK_CORNER_RADIUS_CARD 5

#define VK_CORNER_RADIUS_FULL 6

#define VK_CORNER_RADIUS_CUSTOM 7

#define VK_BORDER_NONE 0

#define VK_BORDER_STANDARD 1

#define VK_BORDER_STRONG 2

#define VK_BORDER_CUSTOM 3

#define VK_EVENT_BUTTON_CLICKED 1

#define VK_STACK_GAP_NONE 0

#define VK_STACK_GAP_EXTRA_SMALL 1

#define VK_STACK_GAP_SMALL 2

#define VK_STACK_GAP_MEDIUM 3

#define VK_STACK_GAP_LARGE 4

#define VK_STACK_GAP_EXTRA_LARGE 5

#define VK_STACK_GAP_DOUBLE_EXTRA_LARGE 6

#define VK_ALIGNMENT_START 0

#define VK_ALIGNMENT_CENTER 1

#define VK_ALIGNMENT_END 2

#define VK_ALIGNMENT_STRETCH 3

#define VK_DISTRIBUTION_START 0

#define VK_DISTRIBUTION_CENTER 1

#define VK_DISTRIBUTION_END 2

#define VK_DISTRIBUTION_SPACE_BETWEEN 3

#define VK_DISTRIBUTION_SPACE_AROUND 4

#define VK_DISTRIBUTION_SPACE_EVENLY 5

#define VK_TEXT_ALIGNMENT_START 0

#define VK_TEXT_ALIGNMENT_CENTER 1

#define VK_TEXT_ALIGNMENT_END 2

#define VK_TEXT_ALIGNMENT_JUSTIFIED 3

#define VK_TEXT_COLOR_BLACK 0

#define VK_TEXT_COLOR_WHITE 1

#define VK_BUTTON_COLOR_ACCENT 0

#define VK_BUTTON_COLOR_DESTRUCTIVE 1

typedef struct DividerTokens DividerTokens;

typedef struct EdgeInsets EdgeInsets;

typedef struct FontFamily FontFamily;

typedef struct FontWeight FontWeight;

typedef struct RadiusTokens RadiusTokens;

typedef struct SpacingTokens SpacingTokens;

typedef struct TextStyle TextStyle;

typedef struct Theme Theme;

typedef struct Typography Typography;

typedef struct VkRuntime VkRuntime;

typedef struct VkString {
  const uint8_t *pointer;
  size_t length;
} VkString;

typedef struct VkActionEvent {
  uint64_t component_instance_id;
  uint64_t node_id;
  uint64_t action_id;
  uint32_t event_kind;
} VkActionEvent;

typedef struct VkLength {
  uint32_t kind;
  float value;
} VkLength;

typedef struct VkColor {
  uint8_t red;
  uint8_t green;
  uint8_t blue;
  uint8_t alpha;
} VkColor;

typedef struct VkRectangleStyle {
  uint32_t color_kind;
  struct VkColor custom_color;
  uint32_t radius_kind;
  float radius;
  uint32_t border_kind;
  struct VkColor border_color;
  float border_width;
} VkRectangleStyle;































struct VkRuntime *vk_runtime_create(uint64_t component_instance_id);

uint32_t vk_abi_version(void);

struct VkString vk_status_name(int32_t status);

int32_t vk_runtime_destroy(struct VkRuntime *runtime);

int32_t vk_tree_begin(struct VkRuntime *runtime, uint64_t root_node_id);

int32_t vk_tree_abort(struct VkRuntime *runtime);

int32_t vk_end_node(struct VkRuntime *runtime);

int32_t vk_tree_commit(struct VkRuntime *runtime);

int32_t vk_runtime_collect_actions(struct VkRuntime *runtime);

int32_t vk_poll_action(struct VkRuntime *runtime,
                       struct VkActionEvent *output,
                       uint8_t *has_action);

int32_t vk_runtime_run_window(struct VkRuntime *runtime,
                              struct VkString title,
                              float width,
                              float height,
                              uint8_t resizable);

int32_t vk_begin_vstack(struct VkRuntime *runtime,
                        uint64_t node_id,
                        uint32_t gap,
                        uint32_t alignment,
                        uint32_t distribution);

int32_t vk_begin_hstack(struct VkRuntime *runtime,
                        uint64_t node_id,
                        uint32_t gap,
                        uint32_t alignment,
                        uint32_t distribution);

int32_t vk_begin_zstack(struct VkRuntime *runtime, uint64_t node_id, uint32_t alignment);

int32_t vk_push_text(struct VkRuntime *runtime,
                     uint64_t node_id,
                     struct VkString content,
                     float font_size,
                     float line_height,
                     uint16_t weight,
                     uint32_t alignment,
                     uint32_t color);

int32_t vk_push_button(struct VkRuntime *runtime,
                       uint64_t node_id,
                       struct VkString title,
                       uint32_t color,
                       float radius,
                       uint64_t action_id);

int32_t vk_begin_padding(struct VkRuntime *runtime,
                         uint64_t node_id,
                         float top,
                         float right,
                         float bottom,
                         float left);

int32_t vk_begin_frame(struct VkRuntime *runtime,
                       uint64_t node_id,
                       struct VkLength width,
                       struct VkLength height);

int32_t vk_push_rectangle(struct VkRuntime *runtime,
                          uint64_t node_id,
                          struct VkRectangleStyle style);

int32_t vk_begin_background(struct VkRuntime *runtime,
                            uint64_t node_id,
                            struct VkRectangleStyle style);

int32_t vk_push_spacer(struct VkRuntime *runtime, uint64_t node_id);

int32_t vk_push_divider(struct VkRuntime *runtime, uint64_t node_id);

#endif  /* VIEWKIT_ABI_H */
