#ifndef VIEWKIT_ABI_H
#define VIEWKIT_ABI_H

/* This file is automatically generated. Do not edit directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define VK_Z_ALIGNMENT_TOP_LEADING 0

#define VK_Z_ALIGNMENT_TOP 1

#define VK_Z_ALIGNMENT_TOP_TRAILING 2

#define VK_Z_ALIGNMENT_LEADING 3

#define VK_Z_ALIGNMENT_CENTER 4

#define VK_Z_ALIGNMENT_TRAILING 5

#define VK_Z_ALIGNMENT_BOTTOM_LEADING 6

#define VK_Z_ALIGNMENT_BOTTOM 7

#define VK_Z_ALIGNMENT_BOTTOM_TRAILING 8

#define VK_ABI_VERSION_MAJOR 1

#define VK_ABI_VERSION_MINOR 0

#define VK_ABI_VERSION_PATCH 0

#define VK_IMAGE_CONTENT_MODE_FIT 0

#define VK_IMAGE_CONTENT_MODE_FILL 1

#define VK_IMAGE_CONTENT_MODE_STRETCH 2

#define VK_IMAGE_SAMPLING_NEAREST 0

#define VK_IMAGE_SAMPLING_BILINEAR 1

#define VK_IMAGE_SAMPLING_BICUBIC 2

#define VK_SVG_CONTENT_MODE_FIT 0

#define VK_SVG_CONTENT_MODE_FILL 1

#define VK_SVG_CONTENT_MODE_STRETCH 2

#define VK_ABI_VERSION (((VK_ABI_VERSION_MAJOR << 16) | (VK_ABI_VERSION_MINOR << 8)) | VK_ABI_VERSION_PATCH)

#define VK_LENGTH_AUTO 0

#define VK_LENGTH_FIXED 1

#define VK_RECTANGLE_COLOR_BACKGROUND 0

#define VK_RECTANGLE_COLOR_SURFACE 1

#define VK_RECTANGLE_COLOR_ELEVATED_SURFACE 2

#define VK_RECTANGLE_COLOR_ACCENT 3

#define VK_RECTANGLE_COLOR_DESTRUCTIVE 4

#define VK_RECTANGLE_COLOR_CUSTOM 5

#define VK_CORNER_RADIUS_NONE 0

#define VK_CORNER_RADIUS_SMALL 1

#define VK_CORNER_RADIUS_MEDIUM 2

#define VK_CORNER_RADIUS_LARGE 3

#define VK_CORNER_RADIUS_EXTRA_LARGE 4

#define VK_CORNER_RADIUS_CARD 5

#define VK_CORNER_RADIUS_FULL 6

#define VK_CORNER_RADIUS_CUSTOM 7

#define VK_BORDER_NONE 0

#define VK_BORDER_STANDARD 1

#define VK_BORDER_STRONG 2

#define VK_BORDER_CUSTOM 3

#define VK_SCROLL_AXIS_HORIZONTAL 0

#define VK_SCROLL_AXIS_VERTICAL 1

#define VK_SCROLL_AXIS_BOTH 2

#define VK_SCROLLBAR_HIDDEN 0

#define VK_SCROLLBAR_AUTOMATIC 1

#define VK_SCROLLBAR_ALWAYS 2

#define VK_TEXT_FIELD_SIZE_SMALL 0

#define VK_TEXT_FIELD_SIZE_MEDIUM 1

#define VK_TEXT_FIELD_SIZE_LARGE 2

#define VK_MENU_ENTRY_ITEM 0

#define VK_MENU_ENTRY_SEPARATOR 1

#define VK_EVENT_BUTTON_CLICKED 1

#define VK_STACK_GAP_NONE 0

#define VK_STACK_GAP_EXTRA_SMALL 1

#define VK_STACK_GAP_SMALL 2

#define VK_STACK_GAP_MEDIUM 3

#define VK_STACK_GAP_LARGE 4

#define VK_STACK_GAP_EXTRA_LARGE 5

#define VK_STACK_GAP_DOUBLE_EXTRA_LARGE 6

#define VK_ALIGNMENT_START 0

#define VK_ALIGNMENT_CENTER 1

#define VK_ALIGNMENT_END 2

#define VK_ALIGNMENT_STRETCH 3

#define VK_DISTRIBUTION_START 0

#define VK_DISTRIBUTION_CENTER 1

#define VK_DISTRIBUTION_END 2

#define VK_DISTRIBUTION_SPACE_BETWEEN 3

#define VK_DISTRIBUTION_SPACE_AROUND 4

#define VK_DISTRIBUTION_SPACE_EVENLY 5

#define VK_TEXT_ALIGNMENT_START 0

#define VK_TEXT_ALIGNMENT_CENTER 1

#define VK_TEXT_ALIGNMENT_END 2

#define VK_TEXT_ALIGNMENT_JUSTIFIED 3

#define VK_TEXT_COLOR_BLACK 0

#define VK_TEXT_COLOR_WHITE 1

#define VK_BUTTON_COLOR_ACCENT 0

#define VK_BUTTON_COLOR_DESTRUCTIVE 1

typedef struct DividerTokens DividerTokens;

typedef struct EdgeInsets EdgeInsets;

typedef struct FontFamily FontFamily;

typedef struct FontWeight FontWeight;

typedef struct RadiusTokens RadiusTokens;

typedef struct SpacingTokens SpacingTokens;

typedef struct TextStyle TextStyle;

typedef struct Theme Theme;

typedef struct Typography Typography;

typedef struct VkRuntime VkRuntime;

typedef struct VkString {
  const uint8_t *pointer;
  size_t length;
} VkString;

typedef struct VkActionEvent {
  uint64_t component_instance_id;
  uint64_t node_id;
  uint64_t action_id;
  uint32_t event_kind;
} VkActionEvent;

typedef struct VkLength {
  uint32_t kind;
  float value;
} VkLength;

typedef struct VkColor {
  uint8_t red;
  uint8_t green;
  uint8_t blue;
  uint8_t alpha;
} VkColor;

typedef struct VkRectangleStyle {
  uint32_t color_kind;
  struct VkColor custom_color;
  uint32_t radius_kind;
  float radius;
  uint32_t border_kind;
  struct VkColor border_color;
  float border_width;
} VkRectangleStyle;

typedef struct VkMenuEntry {
  uint32_t kind;
  struct VkString label;
  struct VkString shortcut;
  uint8_t enabled;
  uint8_t danger;
  uint64_t action_id;
} VkMenuEntry;

typedef struct VkMenuEntries {
  const struct VkMenuEntry *pointer;
  size_t length;
} VkMenuEntries;

typedef struct VkSegmentedItem {
  uint64_t value;
  struct VkString label;
  uint8_t enabled;
} VkSegmentedItem;

typedef struct VkSegmentedItems {
  const struct VkSegmentedItem *pointer;
  size_t length;
} VkSegmentedItems;

typedef struct VkBytes {
  const uint8_t *pointer;
  size_t length;
} VkBytes;































struct VkRuntime *vk_runtime_create(uint64_t component_instance_id);

uint32_t vk_abi_version(void);

struct VkString vk_status_name(int32_t status);

int32_t vk_runtime_destroy(struct VkRuntime *runtime);

int32_t vk_tree_begin(struct VkRuntime *runtime, uint64_t root_node_id);

int32_t vk_tree_abort(struct VkRuntime *runtime);

int32_t vk_end_node(struct VkRuntime *runtime);

int32_t vk_tree_commit(struct VkRuntime *runtime);

int32_t vk_runtime_collect_actions(struct VkRuntime *runtime);

int32_t vk_poll_action(struct VkRuntime *runtime,
                       struct VkActionEvent *output,
                       uint8_t *has_action);

int32_t vk_state_get_bool(struct VkRuntime *runtime, uint64_t state_id, uint8_t *output);

int32_t vk_state_set_bool(struct VkRuntime *runtime, uint64_t state_id, uint8_t value);

int32_t vk_state_get_f32(struct VkRuntime *runtime, uint64_t state_id, float *output);

int32_t vk_state_set_f32(struct VkRuntime *runtime, uint64_t state_id, float value);

int32_t vk_state_get_u64(struct VkRuntime *runtime, uint64_t state_id, uint64_t *output);

int32_t vk_state_set_u64(struct VkRuntime *runtime, uint64_t state_id, uint64_t value);

int32_t vk_state_string_length(struct VkRuntime *runtime, uint64_t state_id, size_t *output);

int32_t vk_state_copy_string(struct VkRuntime *runtime,
                             uint64_t state_id,
                             uint8_t *buffer,
                             size_t buffer_length,
                             size_t *output_length);

int32_t vk_state_set_string(struct VkRuntime *runtime, uint64_t state_id, struct VkString value);

int32_t vk_runtime_run_window(struct VkRuntime *runtime,
                              struct VkString title,
                              float width,
                              float height,
                              uint8_t resizable);

int32_t vk_begin_vstack(struct VkRuntime *runtime,
                        uint64_t node_id,
                        uint32_t gap,
                        uint32_t alignment,
                        uint32_t distribution);

int32_t vk_begin_hstack(struct VkRuntime *runtime,
                        uint64_t node_id,
                        uint32_t gap,
                        uint32_t alignment,
                        uint32_t distribution);

int32_t vk_begin_zstack(struct VkRuntime *runtime, uint64_t node_id, uint32_t alignment);

int32_t vk_push_text(struct VkRuntime *runtime,
                     uint64_t node_id,
                     struct VkString content,
                     float font_size,
                     float line_height,
                     uint16_t weight,
                     uint32_t alignment,
                     uint32_t color);

int32_t vk_push_button(struct VkRuntime *runtime,
                       uint64_t node_id,
                       struct VkString title,
                       uint32_t color,
                       float radius,
                       uint64_t action_id);

int32_t vk_begin_padding(struct VkRuntime *runtime,
                         uint64_t node_id,
                         float top,
                         float right,
                         float bottom,
                         float left);

int32_t vk_begin_frame(struct VkRuntime *runtime,
                       uint64_t node_id,
                       struct VkLength width,
                       struct VkLength height);

int32_t vk_push_rectangle(struct VkRuntime *runtime,
                          uint64_t node_id,
                          struct VkRectangleStyle style);

int32_t vk_begin_background(struct VkRuntime *runtime,
                            uint64_t node_id,
                            struct VkRectangleStyle style);

int32_t vk_push_spacer(struct VkRuntime *runtime, uint64_t node_id);

int32_t vk_push_divider(struct VkRuntime *runtime, uint64_t node_id);

int32_t vk_begin_card(struct VkRuntime *runtime, uint64_t node_id, struct VkRectangleStyle style);

int32_t vk_push_checkbox(struct VkRuntime *runtime,
                         uint64_t node_id,
                         uint64_t state_id,
                         uint8_t checked,
                         struct VkString label,
                         uint8_t enabled);

int32_t vk_begin_context_menu(struct VkRuntime *runtime, uint64_t node_id);

int32_t vk_push_ellipse(struct VkRuntime *runtime, uint64_t node_id, struct VkRectangleStyle style);

int32_t vk_begin_group(struct VkRuntime *runtime, uint64_t node_id);

int32_t vk_push_list_row(struct VkRuntime *runtime,
                         uint64_t node_id,
                         struct VkString title,
                         struct VkString subtitle,
                         struct VkString trailing,
                         uint8_t selected,
                         uint8_t enabled,
                         uint64_t action_id);

int32_t vk_push_menu_item(struct VkRuntime *runtime,
                          uint64_t node_id,
                          struct VkString label,
                          struct VkString shortcut,
                          uint8_t enabled,
                          uint8_t danger,
                          uint64_t action_id);

int32_t vk_push_menu(struct VkRuntime *runtime, uint64_t node_id, struct VkMenuEntries entries);

int32_t vk_begin_overlay(struct VkRuntime *runtime, uint64_t node_id, uint32_t alignment);

int32_t vk_push_radio_button(struct VkRuntime *runtime,
                             uint64_t node_id,
                             uint64_t state_id,
                             uint64_t selection,
                             uint64_t value,
                             struct VkString label,
                             uint8_t enabled);

int32_t vk_begin_scroll(struct VkRuntime *runtime,
                        uint64_t node_id,
                        uint64_t state_id,
                        uint32_t axis,
                        uint32_t scrollbar);

int32_t vk_push_segmented_control(struct VkRuntime *runtime,
                                  uint64_t node_id,
                                  uint64_t state_id,
                                  uint64_t selection,
                                  struct VkSegmentedItems items,
                                  uint8_t enabled);

int32_t vk_push_slider(struct VkRuntime *runtime,
                       uint64_t node_id,
                       uint64_t state_id,
                       float value,
                       float minimum,
                       float maximum,
                       float step,
                       struct VkString label,
                       uint8_t enabled);

int32_t vk_push_switch(struct VkRuntime *runtime,
                       uint64_t node_id,
                       uint64_t state_id,
                       uint8_t checked,
                       struct VkString label,
                       uint8_t enabled);

int32_t vk_push_text_field(struct VkRuntime *runtime,
                           uint64_t node_id,
                           uint64_t state_id,
                           struct VkString value,
                           struct VkString placeholder,
                           uint32_t size,
                           float radius,
                           uint8_t enabled,
                           uint8_t invalid);

int32_t vk_push_image(struct VkRuntime *runtime,
                      uint64_t node_id,
                      struct VkBytes data,
                      uint32_t content_mode,
                      uint32_t radius_kind,
                      float radius,
                      float opacity,
                      uint32_t sampling);

int32_t vk_push_svg(struct VkRuntime *runtime,
                    uint64_t node_id,
                    struct VkBytes data,
                    uint32_t content_mode,
                    uint32_t radius_kind,
                    float radius,
                    float opacity,
                    uint8_t tint_enabled,
                    struct VkColor tint);

#endif  /* VIEWKIT_ABI_H */
