use std::env;
use std::error::Error;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use proc_macro2::TokenStream;
use quote::quote;
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{Expr, ExprClosure, File, Ident, Item, Result as SynResult, Token, Type, parenthesized};

mod keyword {
    syn::custom_keyword!(build);
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum ComponentKind {
    Container,
    Leaf,
}

impl Parse for ComponentKind {
    fn parse(input: ParseStream<'_>) -> SynResult<Self> {
        let ident: Ident = input.parse()?;

        match ident.to_string().as_str() {
            "container" => Ok(Self::Container),

            "leaf" => Ok(Self::Leaf),

            _ => Err(syn::Error::new(
                ident.span(),
                "expected `container` or `leaf`",
            )),
        }
    }
}

struct Argument {
    name: Ident,
    ty: Type,

    binding: Option<Ident>,
    conversion: Option<Expr>,
}

impl Parse for Argument {
    fn parse(input: ParseStream<'_>) -> SynResult<Self> {
        let name: Ident = input.parse()?;

        input.parse::<Token![:]>()?;

        let ty: Type = input.parse()?;

        let (binding, conversion) = if input.peek(Token![=>]) {
            input.parse::<Token![=>]>()?;

            let binding: Ident = input.parse()?;

            input.parse::<Token![=]>()?;

            let conversion: Expr = input.parse()?;

            (Some(binding), Some(conversion))
        } else {
            (None, None)
        };

        Ok(Self {
            name,
            ty,
            binding,
            conversion,
        })
    }
}

struct Component {
    kind: ComponentKind,
    name: Ident,

    arguments: Vec<Argument>,

    factory: ExprClosure,
}

impl Parse for Component {
    fn parse(input: ParseStream<'_>) -> SynResult<Self> {
        let kind: ComponentKind = input.parse()?;

        let name: Ident = input.parse()?;

        let arguments_content;

        parenthesized!(
            arguments_content
            in input
        );

        let arguments = Punctuated::<Argument, Token![,]>::parse_terminated(&arguments_content)?
            .into_iter()
            .collect();

        input.parse::<keyword::build>()?;

        let factory: ExprClosure = input.parse()?;

        input.parse::<Token![;]>()?;

        if factory.capture.is_none() {
            return Err(syn::Error::new_spanned(
                &factory,
                "build closure must be `move`",
            ));
        }

        if factory.inputs.len() != 3 {
            return Err(syn::Error::new_spanned(
                &factory,
                "build closure must accept node_id, children and context",
            ));
        }

        Ok(Self {
            kind,
            name,
            arguments,
            factory,
        })
    }
}

struct Manifest {
    components: Vec<Component>,
}

impl Parse for Manifest {
    fn parse(input: ParseStream<'_>) -> SynResult<Self> {
        let mut components = Vec::new();

        while !input.is_empty() {
            components.push(input.parse()?);
        }

        Ok(Self { components })
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut arguments = env::args_os().skip(1);

    let input = arguments
        .next()
        .map(PathBuf::from)
        .ok_or_else(|| invalid_input("components/mod.rsが指定されていません"))?;

    let output = arguments
        .next()
        .map(PathBuf::from)
        .ok_or_else(|| invalid_input("出力ファイルが指定されていません"))?;

    if arguments.next().is_some() {
        return Err(invalid_input("引数が多すぎます").into());
    }

    let source = fs::read_to_string(&input)?;

    let file: File = syn::parse_file(&source)?;

    let tokens = find_manifest(&file)?;

    let manifest: Manifest = syn::parse2(tokens)?;

    let generated = generate(&manifest);

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }

    write_if_changed(&output, &generated)?;

    Ok(())
}

fn find_manifest(file: &File) -> Result<TokenStream, Box<dyn Error>> {
    for item in &file.items {
        let Item::Macro(item_macro) = item else {
            continue;
        };

        let Some(segment) = item_macro.mac.path.segments.last() else {
            continue;
        };

        if segment.ident == "ffi_components" {
            return Ok(item_macro.mac.tokens.clone());
        }
    }

    Err(invalid_input("ffi_components!が見つかりません").into())
}

fn generate(manifest: &Manifest) -> String {
    let functions = manifest.components.iter().map(generate_component);

    let output = quote! {
        use super::*;

        use super::tree::{
            FfiBuiltView,
            FfiNode,
            FfiViewFactory,
            expect_no_children,
            into_stack_children,
            zero_or_one_stack_child,
            zero_or_one_view,
        };

        #(#functions)*
    };

    format!(
        concat!(
            "// @generated by tools/ffi-gen.\n",
            "// Do not edit manually.\n\n",
            "{}\n",
        ),
        output,
    )
}

fn generate_component(component: &Component) -> TokenStream {
    let name = &component.name;

    let argument_names = component.arguments.iter().map(|argument| &argument.name);

    let argument_types = component.arguments.iter().map(|argument| &argument.ty);

    let conversions = component.arguments.iter().filter_map(|argument| {
        let binding = argument.binding.as_ref()?;

        let conversion = argument.conversion.as_ref()?;

        Some(quote! {
            let #binding =
                #conversion;
        })
    });

    let factory = &component.factory;

    let builder_method = match component.kind {
        ComponentKind::Container => Ident::new("begin", name.span()),

        ComponentKind::Leaf => Ident::new("leaf", name.span()),
    };

    quote! {
        #[unsafe(no_mangle)]
        #[allow(
            clippy::too_many_arguments
        )]
        pub extern "C" fn #name(
            runtime: *mut VkRuntime,
            node_id: u64,

            #(
                #argument_names:
                    #argument_types,
            )*
        ) -> i32 {
            ffi_status(|| {
                #(#conversions)*

                let factory:
                    FfiViewFactory =
                    Box::new(#factory);

                let runtime =
                    runtime_mut(runtime)?;

                let builder =
                    active_builder(runtime)?;

                let node =
                    FfiNode::component(
                        node_id,
                        factory,
                    );

                builder
                    .#builder_method(
                        node,
                    );

                Ok(())
            })
        }
    }
}

fn write_if_changed(path: &Path, content: &str) -> io::Result<()> {
    if fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }

    fs::write(path, content)
}

fn invalid_input(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}
