use serde::Deserialize;
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct Manifest {
    component: Vec<Component>,
}

#[derive(Clone, Copy, Debug, Deserialize)]
#[serde(rename_all = "snake_case")]
enum ComponentKind {
    Container,
    Leaf,
}

#[derive(Debug, Deserialize)]
struct Component {
    name: String,
    kind: ComponentKind,

    #[serde(default)]
    arguments: Vec<Argument>,

    node: String,
}

#[derive(Debug, Deserialize)]
struct Argument {
    name: String,

    #[serde(rename = "type")]
    ty: String,

    bind: Option<String>,
    convert: Option<String>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut arguments = env::args_os().skip(1);

    let input = arguments
        .next()
        .map(PathBuf::from)
        .ok_or_else(|| invalid_input("入力ファイルが指定されていません"))?;

    let output = arguments
        .next()
        .map(PathBuf::from)
        .ok_or_else(|| invalid_input("出力ファイルが指定されていません"))?;

    if arguments.next().is_some() {
        return Err(invalid_input("引数が多すぎます").into());
    }

    let manifest_source = fs::read_to_string(&input)?;
    let manifest: Manifest = toml::from_str(&manifest_source)?;

    validate_manifest(&manifest)?;

    let generated = generate(&manifest)?;

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }

    write_if_changed(&output, &generated)?;

    Ok(())
}

fn generate(manifest: &Manifest) -> Result<String, std::fmt::Error> {
    let mut output = String::new();

    writeln!(
        output,
        "// @generated by tools/ffi-gen. Do not edit manually."
    )?;
    writeln!(output)?;
    writeln!(output, "use super::*;")?;
    writeln!(
        output,
        "use crate::runtime::{{\
        ActionId, \
        ButtonNode, \
        FrameNode, \
        HStackNode, \
        NodeId, \
        PaddingNode, \
        TextNode, \
        VStackNode, \
        ViewNode, \
        ViewNodeKind, \
        ZStackNode, \
    }};"
    )?;
    writeln!(output)?;

    for component in &manifest.component {
        generate_component(&mut output, component)?;
    }

    Ok(output)
}

fn generate_component(output: &mut String, component: &Component) -> Result<(), std::fmt::Error> {
    writeln!(output, "#[unsafe(no_mangle)]")?;
    writeln!(output, "#[allow(clippy::too_many_arguments)]")?;
    writeln!(output, "pub extern \"C\" fn {}(", component.name)?;
    writeln!(output, "    runtime: *mut VkRuntime,")?;
    writeln!(output, "    node_id: u64,")?;

    for argument in &component.arguments {
        writeln!(output, "    {}: {},", argument.name, argument.ty,)?;
    }

    writeln!(output, ") -> i32 {{")?;
    writeln!(output, "    ffi_status(|| {{")?;

    for argument in &component.arguments {
        match (&argument.bind, &argument.convert) {
            (bind, Some(convert)) => {
                let binding = bind.as_deref().unwrap_or(argument.name.as_str());

                writeln!(output, "        let {binding} = {convert};",)?;
            }

            (Some(bind), None) if bind != &argument.name => {
                writeln!(output, "        let {bind} = {};", argument.name,)?;
            }

            _ => {}
        }
    }

    if !component.arguments.is_empty() {
        writeln!(output)?;
    }

    writeln!(output, "        let runtime = runtime_mut(runtime)?;",)?;
    writeln!(output, "        let builder = active_builder(runtime)?;",)?;
    writeln!(output)?;
    writeln!(output, "        let node = {};", component.node.trim(),)?;
    writeln!(output)?;

    let builder_method = match component.kind {
        ComponentKind::Container => "begin",
        ComponentKind::Leaf => "leaf",
    };

    writeln!(
        output,
        "        builder.{builder_method}(ViewNode::new(NodeId(node_id), node));",
    )?;
    writeln!(output)?;
    writeln!(output, "        Ok(())")?;
    writeln!(output, "    }})")?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    Ok(())
}

fn validate_manifest(manifest: &Manifest) -> Result<(), Box<dyn Error>> {
    for component in &manifest.component {
        if !component.name.starts_with("vk_") || !is_identifier(&component.name) {
            return Err(invalid_input(format!("不正なFFI関数名です: {}", component.name,)).into());
        }

        for argument in &component.arguments {
            if !is_identifier(&argument.name) {
                return Err(invalid_input(format!(
                    "{}の引数名が不正です: {}",
                    component.name, argument.name,
                ))
                .into());
            }

            if let Some(bind) = argument.bind.as_deref()
                && !is_identifier(bind)
            {
                return Err(invalid_input(format!(
                    "{}のbinding名が不正です: {}",
                    component.name, bind,
                ))
                .into());
            }

            if argument.ty.trim().is_empty() {
                return Err(invalid_input(format!(
                    "{}::{}の型が空です",
                    component.name, argument.name,
                ))
                .into());
            }
        }

        if component.node.trim().is_empty() {
            return Err(invalid_input(format!("{}のnode式が空です", component.name,)).into());
        }
    }

    Ok(())
}

fn is_identifier(value: &str) -> bool {
    let mut characters = value.chars();

    let Some(first) = characters.next() else {
        return false;
    };

    if first != '_' && !first.is_ascii_alphabetic() {
        return false;
    }

    characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn write_if_changed(path: &Path, content: &str) -> io::Result<()> {
    if fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return Ok(());
    }

    fs::write(path, content)
}

fn invalid_input(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}
