use super::{Color, ColorTokens, Shadow, ShadowSet};

/// Colors and elevation used by desktop-shell surfaces.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ShellTokens {
    pub bar_background: Color,
    pub window_background: Color,
    pub window_border: Color,
    pub title_bar_background: Color,
    pub title_bar_border: Color,
    pub primary_text: Color,
    pub secondary_text: Color,
    pub tertiary_text: Color,
    pub control: Color,
    pub control_hover: Color,
    pub close_hover: Color,
    pub close_pressed: Color,
    pub content_background: Color,
    pub scrim: Color,
    pub panel_background: Color,
    pub panel_border: Color,
    pub field_background: Color,
    pub field_border: Color,
    pub selection_soft: Color,
    pub selection_border: Color,
    pub item_hover: Color,
    pub item_enabled: Color,
    pub item_disabled: Color,
    pub inverse_surface: Color,
    pub inverse_text: Color,
    pub action: Color,
    pub action_hover: Color,
    pub action_pressed: Color,
    pub alert: Color,
    pub dock_background: Color,
    pub dock_border: Color,
    pub dock_item_hover: Color,
    pub running_indicator: Color,
    pub inactive_window_shadow: ShadowSet,
    pub active_window_shadow: ShadowSet,
    pub panel_shadow: ShadowSet,
    pub dock_shadow: ShadowSet,
}

impl ShellTokens {
    pub const LIGHT: Self = Self {
        bar_background: Color::rgba(250, 250, 250, 100),
        window_background: Color::rgba(250, 250, 250, 235),
        window_border: Color::rgba(0, 0, 0, 31),
        title_bar_background: Color::rgba(255, 255, 255, 245),
        title_bar_border: Color::rgba(0, 0, 0, 26),
        primary_text: Color::from_rgb_hex(0x191919),
        secondary_text: Color::from_rgb_hex(0x626262),
        tertiary_text: Color::rgba(60, 60, 67, 170),
        control: Color::from_rgb_hex(0x202020),
        control_hover: Color::rgba(0, 0, 0, 17),
        close_hover: Color::from_rgb_hex(0xe81123),
        close_pressed: Color::from_rgb_hex(0xc50f1f),
        content_background: Color::from_rgb_hex(0xfafafa),
        scrim: Color::rgba(0, 0, 0, 72),
        panel_background: Color::rgba(247, 247, 249, 246),
        panel_border: Color::rgba(255, 255, 255, 180),
        field_background: Color::rgba(255, 255, 255, 232),
        field_border: Color::rgba(0, 0, 0, 30),
        selection_soft: Color::rgba(0, 122, 255, 28),
        selection_border: Color::rgba(0, 122, 255, 72),
        item_hover: Color::rgba(0, 0, 0, 12),
        item_enabled: Color::rgba(0, 0, 0, 14),
        item_disabled: Color::rgba(0, 0, 0, 5),
        inverse_surface: Color::rgba(38, 38, 38, 230),
        inverse_text: Color::WHITE,
        action: Color::from_rgb_hex(0x1a73e8),
        action_hover: Color::from_rgb_hex(0x2878d0),
        action_pressed: Color::from_rgb_hex(0x1557b0),
        alert: Color::from_rgb_hex(0xd93025),
        dock_background: Color::rgba(255, 255, 255, 190),
        dock_border: Color::rgba(0, 0, 0, 28),
        dock_item_hover: Color::rgba(255, 255, 255, 225),
        running_indicator: Color::rgba(45, 45, 45, 210),
        inactive_window_shadow: ShadowSet::single(Shadow::new(
            Color::rgba(0, 0, 0, 8),
            0.0,
            2.0,
            5.0,
            1.0,
        )),
        active_window_shadow: ShadowSet::double(
            Shadow::new(Color::rgba(0, 0, 0, 20), 0.0, 2.0, 5.0, 0.0),
            Shadow::new(Color::rgba(0, 0, 0, 28), 0.0, 5.0, 14.0, 0.0),
        ),
        panel_shadow: ShadowSet::single(Shadow::new(
            Color::rgba(0, 0, 0, 44),
            0.0,
            12.0,
            32.0,
            0.0,
        )),
        dock_shadow: ShadowSet::single(Shadow::new(Color::rgba(0, 0, 0, 18), 0.0, 4.0, 12.0, 0.0)),
    };

    pub const DARK: Self = Self {
        bar_background: Color::rgba(28, 28, 30, 180),
        window_background: Color::rgba(36, 36, 38, 245),
        window_border: Color::rgba(255, 255, 255, 38),
        title_bar_background: Color::rgba(44, 44, 46, 245),
        title_bar_border: Color::rgba(255, 255, 255, 26),
        primary_text: Color::from_rgb_hex(0xf5f5f7),
        secondary_text: Color::from_rgb_hex(0xaeaeb2),
        tertiary_text: Color::rgba(235, 235, 245, 153),
        control: Color::from_rgb_hex(0xf5f5f7),
        control_hover: Color::rgba(255, 255, 255, 24),
        close_hover: Color::from_rgb_hex(0xff453a),
        close_pressed: Color::from_rgb_hex(0xd9362e),
        content_background: Color::from_rgb_hex(0x242426),
        scrim: Color::rgba(0, 0, 0, 112),
        panel_background: Color::rgba(44, 44, 46, 246),
        panel_border: Color::rgba(255, 255, 255, 38),
        field_background: Color::rgba(58, 58, 60, 232),
        field_border: Color::rgba(255, 255, 255, 35),
        selection_soft: Color::rgba(10, 132, 255, 48),
        selection_border: Color::rgba(10, 132, 255, 112),
        item_hover: Color::rgba(255, 255, 255, 18),
        item_enabled: Color::rgba(255, 255, 255, 22),
        item_disabled: Color::rgba(255, 255, 255, 8),
        inverse_surface: Color::rgba(245, 245, 247, 235),
        inverse_text: Color::from_rgb_hex(0x1d1d1f),
        action: Color::from_rgb_hex(0x409cff),
        action_hover: Color::from_rgb_hex(0x64adff),
        action_pressed: Color::from_rgb_hex(0x0a84ff),
        alert: Color::from_rgb_hex(0xff453a),
        dock_background: Color::rgba(44, 44, 46, 210),
        dock_border: Color::rgba(255, 255, 255, 32),
        dock_item_hover: Color::rgba(255, 255, 255, 30),
        running_indicator: Color::rgba(245, 245, 247, 210),
        inactive_window_shadow: Self::LIGHT.inactive_window_shadow,
        active_window_shadow: Self::LIGHT.active_window_shadow,
        panel_shadow: Self::LIGHT.panel_shadow,
        dock_shadow: Self::LIGHT.dock_shadow,
    };
}

/// Colors used by file and object browsers.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct BrowserTokens {
    pub window_background: Color,
    pub toolbar_background: Color,
    pub sidebar_background: Color,
    pub content_background: Color,
    pub border: Color,
    pub text_primary: Color,
    pub text_secondary: Color,
    pub row_hover: Color,
    pub selection: Color,
    pub on_selection: Color,
    pub field_background: Color,
    pub field_focused: Color,
    pub disabled: Color,
    pub sidebar_selection: Color,
    pub sidebar_hover: Color,
    pub list_header: Color,
    pub control_hover: Color,
    pub control_selection: Color,
    pub control_selection_hover: Color,
}

impl BrowserTokens {
    pub const fn from_colors(colors: ColorTokens) -> Self {
        Self {
            window_background: colors.background,
            toolbar_background: colors.surface_subtle,
            sidebar_background: colors.surface_subtle,
            content_background: colors.surface,
            border: colors.border,
            text_primary: colors.text_primary,
            text_secondary: colors.text_secondary,
            row_hover: colors.surface_subtle,
            selection: colors.accent,
            on_selection: Color::WHITE,
            field_background: colors.surface_muted,
            field_focused: colors.surface,
            disabled: colors.text_disabled,
            sidebar_selection: colors.accent_soft,
            sidebar_hover: colors.surface_muted,
            list_header: colors.surface_subtle,
            control_hover: colors.surface_muted,
            control_selection: colors.accent_soft,
            control_selection_hover: colors.surface_subtle,
        }
    }
}
