#[derive(Clone, Copy, Debug, PartialEq)]
pub struct LayoutTokens {
    pub navigation_sidebar_width: f32,
    pub top_bar_height: f32,
    pub bottom_bar_height: f32,
    pub list_row_height: f32,
    pub list_leading_size: f32,
    pub status_marker_size: f32,
    pub avatar_small_size: f32,
    pub avatar_size: f32,
    pub icon_button_size: f32,
    pub prominent_icon_button_size: f32,
    pub checkbox_size: f32,
    pub checkbox_glyph_size: f32,
    pub checkbox_radius: f32,
    pub compact_control_height: f32,
    pub control_height: f32,
    pub large_control_height: f32,
    pub dialog_width: f32,
    pub dialog_height: f32,
    pub popover_width: f32,
    pub popover_height: f32,
    pub control_min_width: f32,
    pub tab_width: f32,
    pub compact_icon_size: f32,
    pub stepper_icon_size: f32,
    pub radio_size: f32,
    pub radio_inset: f32,
    pub radio_dot_size: f32,
    pub range_control_width: f32,
    pub range_control_height: f32,
    pub range_track_height: f32,
    pub message_max_width: f32,
    pub range_knob_size: f32,
    pub range_dragging_knob_size: f32,
    pub range_hit_padding: f32,
    pub switch_track_width: f32,
    pub switch_track_height: f32,
    pub switch_knob_size: f32,
    pub switch_pressed_knob_width: f32,
    pub switch_knob_inset: f32,
    pub switch_drag_threshold: f32,
    pub switch_hit_padding: f32,
    pub segmented_control_inset: f32,
    pub segmented_control_height: f32,
    pub segmented_item_min_width: f32,
}

impl LayoutTokens {
    pub const DEFAULT: Self = Self {
        navigation_sidebar_width: 320.0,
        top_bar_height: 64.0,
        bottom_bar_height: 56.0,
        list_row_height: 64.0,
        list_leading_size: 24.0,
        status_marker_size: 8.0,
        avatar_small_size: 24.0,
        avatar_size: 32.0,
        icon_button_size: 24.0,
        prominent_icon_button_size: 32.0,
        checkbox_size: 12.0,
        checkbox_glyph_size: 10.0,
        checkbox_radius: 4.0,
        compact_control_height: 24.0,
        control_height: 32.0,
        large_control_height: 40.0,
        dialog_width: 360.0,
        dialog_height: 200.0,
        popover_width: 240.0,
        popover_height: 120.0,
        control_min_width: 120.0,
        tab_width: 72.0,
        compact_icon_size: 12.0,
        stepper_icon_size: 18.0,
        radio_size: 22.0,
        radio_inset: 3.0,
        radio_dot_size: 6.0,
        range_control_width: 160.0,
        range_control_height: 24.0,
        range_track_height: 4.0,
        message_max_width: 360.0,
        range_knob_size: 12.0,
        range_dragging_knob_size: 12.0,
        range_hit_padding: 8.0,
        switch_track_width: 40.0,
        switch_track_height: 22.0,
        switch_knob_size: 18.0,
        switch_pressed_knob_width: 22.0,
        switch_knob_inset: 2.0,
        switch_drag_threshold: 3.0,
        switch_hit_padding: 6.0,
        segmented_control_inset: 2.0,
        segmented_control_height: 30.0,
        segmented_item_min_width: 64.0,
    };
}
