// @generated by tools/ffi-gen. Do not edit manually.

use super::*;
use crate::runtime::{
    ActionId, ButtonNode, FrameNode, HStackNode, NodeId, PaddingNode, TextNode, VStackNode,
    ViewNode, ViewNodeKind, ZStackNode,
};

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_vstack(
    runtime: *mut VkRuntime,
    node_id: u64,
    gap: u32,
    alignment: u32,
    distribution: u32,
) -> i32 {
    ffi_status(|| {
        let gap = decode_stack_gap(gap)?;
        let alignment = decode_stack_alignment(alignment)?;
        let distribution = decode_stack_distribution(distribution)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::VStack(VStackNode {
            gap,
            alignment,
            distribution,
        });

        builder.begin(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_hstack(
    runtime: *mut VkRuntime,
    node_id: u64,
    gap: u32,
    alignment: u32,
    distribution: u32,
) -> i32 {
    ffi_status(|| {
        let gap = decode_stack_gap(gap)?;
        let alignment = decode_stack_alignment(alignment)?;
        let distribution = decode_stack_distribution(distribution)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::HStack(HStackNode {
            gap,
            alignment,
            distribution,
        });

        builder.begin(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_zstack(runtime: *mut VkRuntime, node_id: u64, alignment: u32) -> i32 {
    ffi_status(|| {
        let alignment = decode_zstack_alignment(alignment)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::ZStack(ZStackNode { alignment });

        builder.begin(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_padding(
    runtime: *mut VkRuntime,
    node_id: u64,
    top: f32,
    right: f32,
    bottom: f32,
    left: f32,
) -> i32 {
    ffi_status(|| {
        let top = sanitize_length(top);
        let right = sanitize_length(right);
        let bottom = sanitize_length(bottom);
        let left = sanitize_length(left);

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Padding(PaddingNode {
            top,
            right,
            bottom,
            left,
        });

        builder.begin(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_frame(
    runtime: *mut VkRuntime,
    node_id: u64,
    width: VkLength,
    height: VkLength,
) -> i32 {
    ffi_status(|| {
        let width = decode_layout_length(width)?;
        let height = decode_layout_length(height)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Frame(FrameNode { width, height });

        builder.begin(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_background(
    runtime: *mut VkRuntime,
    node_id: u64,
    style: VkRectangleStyle,
) -> i32 {
    ffi_status(|| {
        let properties = decode_rectangle_style(style)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Background(properties);

        builder.begin(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_text(
    runtime: *mut VkRuntime,
    node_id: u64,
    content: VkString,
    font_size: f32,
    line_height: f32,
    weight: u16,
    alignment: u32,
    color: u32,
) -> i32 {
    ffi_status(|| {
        let content = copy_string(content)?;
        let font_size = finite_or_default(font_size, 16.0);
        let line_height = finite_or_default(line_height, 24.0);
        let alignment = decode_text_alignment(alignment)?;
        let color = decode_text_color(color)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Text(TextNode {
            content,
            font_family: String::from("Noto Sans JP"),
            font_size,
            line_height,
            weight,
            alignment,
            color,
        });

        builder.leaf(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_button(
    runtime: *mut VkRuntime,
    node_id: u64,
    title: VkString,
    color: u32,
    radius: f32,
    action_id: u64,
) -> i32 {
    ffi_status(|| {
        let title = copy_string(title)?;
        let color = decode_button_color(color)?;
        let radius = sanitize_length(radius);
        let action = if action_id == 0 {
            None
        } else {
            Some(ActionId(action_id))
        };

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Button(ButtonNode {
            title,
            color,
            radius,
            action,
        });

        builder.leaf(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_spacer(runtime: *mut VkRuntime, node_id: u64) -> i32 {
    ffi_status(|| {
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Spacer;

        builder.leaf(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_divider(runtime: *mut VkRuntime, node_id: u64) -> i32 {
    ffi_status(|| {
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Divider;

        builder.leaf(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}

#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_rectangle(
    runtime: *mut VkRuntime,
    node_id: u64,
    style: VkRectangleStyle,
) -> i32 {
    ffi_status(|| {
        let properties = decode_rectangle_style(style)?;

        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;

        let node = ViewNodeKind::Rectangle(properties);

        builder.leaf(ViewNode::new(NodeId(node_id), node));

        Ok(())
    })
}
