// @generated by tools/ffi-gen.
// Do not edit manually.

use super::tree::{
    FfiBuiltView, FfiNode, FfiViewFactory, expect_no_children, into_stack_children,
    zero_or_one_stack_child, zero_or_one_view,
};
use super::*;
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_vstack(
    runtime: *mut VkRuntime,
    node_id: u64,
    gap: u32,
    alignment: u32,
    distribution: u32,
) -> i32 {
    ffi_status(|| {
        let gap = decode_stack_gap(gap)?;
        let alignment = decode_stack_alignment(alignment)?;
        let distribution = decode_stack_distribution(distribution)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            let children = into_stack_children(children);
            Ok(FfiBuiltView::View(Box::new(
                crate::components::VStack::new()
                    .gap(gap)
                    .alignment(alignment)
                    .distribution(distribution)
                    .children(children),
            )))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.begin(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_hstack(
    runtime: *mut VkRuntime,
    node_id: u64,
    gap: u32,
    alignment: u32,
    distribution: u32,
) -> i32 {
    ffi_status(|| {
        let gap = decode_stack_gap(gap)?;
        let alignment = decode_stack_alignment(alignment)?;
        let distribution = decode_stack_distribution(distribution)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            let children = into_stack_children(children);
            Ok(FfiBuiltView::View(Box::new(
                crate::components::HStack::new()
                    .gap(gap)
                    .alignment(alignment)
                    .distribution(distribution)
                    .children(children),
            )))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.begin(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_zstack(runtime: *mut VkRuntime, node_id: u64, alignment: u32) -> i32 {
    ffi_status(|| {
        let alignment = decode_zstack_alignment(alignment)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            let children = into_stack_children(children);
            Ok(FfiBuiltView::View(Box::new(
                crate::components::ZStack::new()
                    .alignment(alignment)
                    .children(children),
            )))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.begin(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_text(
    runtime: *mut VkRuntime,
    node_id: u64,
    content: VkString,
    font_size: f32,
    line_height: f32,
    weight: u16,
    alignment: u32,
    color: u32,
) -> i32 {
    ffi_status(|| {
        let content = copy_string(content)?;
        let font_size = finite_or_default(font_size, 16.0);
        let line_height = finite_or_default(line_height, 24.0);
        let alignment = decode_text_alignment(alignment)?;
        let color = decode_text_color(color)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            expect_no_children(children)?;
            Ok(FfiBuiltView::View(Box::new(
                crate::components::Text::new(content)
                    .font_family("Noto Sans JP")
                    .font_size(font_size)
                    .line_height(line_height)
                    .weight(weight)
                    .alignment(alignment)
                    .color(color),
            )))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.leaf(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_button(
    runtime: *mut VkRuntime,
    node_id: u64,
    title: VkString,
    color: u32,
    radius: f32,
    action_id: u64,
) -> i32 {
    ffi_status(|| {
        let title = copy_string(title)?;
        let color = decode_button_color(color)?;
        let radius = sanitize_length(radius);
        let factory: FfiViewFactory = Box::new(move |node_id, children, context| {
            expect_no_children(children)?;
            let mut button = crate::components::Button::new(title)
                .color(color)
                .radius(crate::theme::CornerRadius::Custom(radius));
            if action_id != 0 {
                button = button.on_click(context.button_callback(node_id, action_id));
            }
            Ok(FfiBuiltView::View(Box::new(button)))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.leaf(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_padding(
    runtime: *mut VkRuntime,
    node_id: u64,
    top: f32,
    right: f32,
    bottom: f32,
    left: f32,
) -> i32 {
    ffi_status(|| {
        let top = sanitize_length(top);
        let right = sanitize_length(right);
        let bottom = sanitize_length(bottom);
        let left = sanitize_length(left);
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            let content = zero_or_one_view(children)?;
            Ok(FfiBuiltView::View(Box::new(
                crate::components::Padding::only(top, right, bottom, left).content(content),
            )))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.begin(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_frame(
    runtime: *mut VkRuntime,
    node_id: u64,
    width: VkLength,
    height: VkLength,
) -> i32 {
    ffi_status(|| {
        let width = decode_layout_length(width)?;
        let height = decode_layout_length(height)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            let mut child = zero_or_one_stack_child(children)?;
            if let crate::layout::LayoutLength::Fixed(width) = width {
                child = child.width(width);
            }
            if let crate::layout::LayoutLength::Fixed(height) = height {
                child = child.height(height);
            }
            Ok(FfiBuiltView::StackChild(child))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.begin(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_rectangle(
    runtime: *mut VkRuntime,
    node_id: u64,
    style: VkRectangleStyle,
) -> i32 {
    ffi_status(|| {
        let style = decode_rectangle_style(style)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            expect_no_children(children)?;
            Ok(FfiBuiltView::View(Box::new(build_rectangle(style))))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.leaf(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_begin_background(
    runtime: *mut VkRuntime,
    node_id: u64,
    style: VkRectangleStyle,
) -> i32 {
    ffi_status(|| {
        let style = decode_rectangle_style(style)?;
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            let content = zero_or_one_view(children)?;
            Ok(FfiBuiltView::View(Box::new(
                crate::components::Background::new()
                    .background(build_rectangle(style))
                    .content(content),
            )))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.begin(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_spacer(runtime: *mut VkRuntime, node_id: u64) -> i32 {
    ffi_status(|| {
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            expect_no_children(children)?;
            Ok(FfiBuiltView::StackChild(
                crate::layout::IntoStackChild::into_stack_child(crate::components::Spacer::new()),
            ))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.leaf(node);
        Ok(())
    })
}
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "C" fn vk_push_divider(runtime: *mut VkRuntime, node_id: u64) -> i32 {
    ffi_status(|| {
        let factory: FfiViewFactory = Box::new(move |_node_id, children, _context| {
            expect_no_children(children)?;
            Ok(FfiBuiltView::StackChild(
                crate::layout::IntoStackChild::into_stack_child(crate::components::Divider::new()),
            ))
        });
        let runtime = runtime_mut(runtime)?;
        let builder = active_builder(runtime)?;
        let node = FfiNode::component(node_id, factory);
        builder.leaf(node);
        Ok(())
    })
}
